service: hta-platform

frameworkVersion: "3"

provider:
  name: aws
  runtime: provided.al2
  region: ap-southeast-1
  architecture: x86_64
  memorySize: 512
  timeout: 10

functions:
  api:
    handler: bootstrap
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  individually: true
  patterns:
    - "!./**"
    - ./bootstrap
    - ./.env
